### ISSUE TITLE
Question and Requesting for json files

### ISSUE THREAD

**Issue by redleaf-kim** [XLearning-SCU/2024-ICLR-READ#9]
First of all, thank you for the fantastic work and for sharing this project with the community.

I’m currently trying to reproduce the results from your paper, but so far, I haven’t been able to achieve the performance mentioned in the paper. I was wondering if it would be possible to share the corruption JSON files used in your experiments?

Additionally, I noticed a potential issue with the JSON item order for the corruption data generated by create_audio_c_json.py and create_visual_c_json.py. As far as I understand, both scripts generate the JSON files with random shuffling but without fixing a random seed. This seems to result in different outputs each time the JSON files are created, potentially affecting reproducibility.

Could you confirm if this is the intended behavior? If so, do you recommend a specific approach to ensure consistency when generating these files?

https://github.com/XLearning-SCU/2024-ICLR-READ/blob/f233f4e5a01100c26d56cfdfdb192fa3d8801512/data_process/create_audio_c_json.py#L53-L56

**Comment by mouxingyang** [comment]
Hi, we have provided JSON files as references and you can custom your own JSON files by using scripts in Step2.

We have successfully reproduce the results multiple times using newly-generated corruption JSON files. For your reproduce, we will upload the recently-produced corruption JSON files in the "json_csv_files" folder, which would help to reproduce the results.

**Comment by redleaf-kim** [comment]
Thanks for your response and for sharing the JSON files :) 
Looking forward to more of your great work in the future. Thanks again!
